# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0e40b39873b5a5fe097f1e8a981e6b714f4e7ad1109be7c800279d50654d3f279eb29eb46411ab1442cece6710e577adee12592603290fce2703ed370ca531c0

test:
  secret_key_base: ab28fe8d17030783bea7fb3024b18810a061c1af0157c806eeb606a8a70f55acfcab4ab4d51c55bdec06de079e4a13474fc1e4dac40c159b4c624ed3993a15fa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
